# Generated by Django 5.1.15 on 2026-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
