# Generated by Django 5.1.15 on 2026-05-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_profile_username'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='about.profile'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
